/**
 * Service with Swagger-UI
 * C++/oat++ Web Service with Swagger-UI
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef OAI_OAIDefaultApi_H
#define OAI_OAIDefaultApi_H

#include "OAIHelpers.h"
#include "OAIHttpRequest.h"
#include "OAIServerConfiguration.h"
#include "OAIOauth.h"

#include "OAIMyMessageDto.h"
#include "OAIMyTemperatureDto.h"
#include <QString>

#include <QObject>
#include <QByteArray>
#include <QStringList>
#include <QList>
#include <QNetworkAccessManager>

namespace OpenAPI {

class OAIDefaultApi : public QObject {
    Q_OBJECT

public:
    OAIDefaultApi(const int timeOut = 0);
    ~OAIDefaultApi();

    void initializeServerConfigs();
    int setDefaultServerValue(int serverIndex,const QString &operation, const QString &variable,const QString &val);
    void setServerIndex(const QString &operation, int serverIndex);
    void setApiKey(const QString &apiKeyName, const QString &apiKey);
    void setBearerToken(const QString &token);
    void setUsername(const QString &username);
    void setPassword(const QString &password);
    void setTimeOut(const int timeOut);
    void setWorkingDirectory(const QString &path);
    void setNetworkAccessManager(QNetworkAccessManager* manager);
    int addServerConfiguration(const QString &operation, const QUrl &url, const QString &description = "", const QMap<QString, OAIServerVariable> &variables = QMap<QString, OAIServerVariable>());
    void setNewServerForAllOperations(const QUrl &url, const QString &description = "", const QMap<QString, OAIServerVariable> &variables =  QMap<QString, OAIServerVariable>());
    void setNewServer(const QString &operation, const QUrl &url, const QString &description = "", const QMap<QString, OAIServerVariable> &variables =  QMap<QString, OAIServerVariable>());
    void addHeaders(const QString &key, const QString &value);
    void enableRequestCompression();
    void enableResponseCompression();
    void abortRequests();
    QString getParamStylePrefix(const QString &style);
    QString getParamStyleSuffix(const QString &style);
    QString getParamStyleDelimiter(const QString &style, const QString &name, bool isExplode);


    void getLastPeriodicMessage();


    void ping();


    void root();


    void temperature();


    void toggleLed();


private:
    QMap<QString,int> _serverIndices;
    QMap<QString,QList<OAIServerConfiguration>> _serverConfigs;
    QMap<QString, QString> _apiKeys;
    QString _bearerToken;
    QString _username;
    QString _password;
    int _timeOut;
    QString _workingDirectory;
    QNetworkAccessManager* _manager;
    QMap<QString, QString> _defaultHeaders;
    bool _isResponseCompressionEnabled;
    bool _isRequestCompressionEnabled;
    OAIHttpRequestInput _latestInput;
    OAIHttpRequestWorker *_latestWorker;
    QStringList _latestScope;
    OauthCode _authFlow;
    OauthImplicit _implicitFlow;
    OauthCredentials _credentialFlow;
    OauthPassword _passwordFlow;
    int _OauthMethod = 0;

    void getLastPeriodicMessageCallback(OAIHttpRequestWorker *worker);
    void pingCallback(OAIHttpRequestWorker *worker);
    void rootCallback(OAIHttpRequestWorker *worker);
    void temperatureCallback(OAIHttpRequestWorker *worker);
    void toggleLedCallback(OAIHttpRequestWorker *worker);

Q_SIGNALS:

    void getLastPeriodicMessageSignal(QString summary);
    void pingSignal(OAIMyMessageDto summary);
    void rootSignal(OAIMyMessageDto summary);
    void temperatureSignal(OAIMyTemperatureDto summary);
    void toggleLedSignal(QString summary);

    void getLastPeriodicMessageSignalFull(OAIHttpRequestWorker *worker, QString summary);
    void pingSignalFull(OAIHttpRequestWorker *worker, OAIMyMessageDto summary);
    void rootSignalFull(OAIHttpRequestWorker *worker, OAIMyMessageDto summary);
    void temperatureSignalFull(OAIHttpRequestWorker *worker, OAIMyTemperatureDto summary);
    void toggleLedSignalFull(OAIHttpRequestWorker *worker, QString summary);

    Q_DECL_DEPRECATED_X("Use getLastPeriodicMessageSignalError() instead")
    void getLastPeriodicMessageSignalE(QString summary, QNetworkReply::NetworkError error_type, QString error_str);
    void getLastPeriodicMessageSignalError(QString summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pingSignalError() instead")
    void pingSignalE(OAIMyMessageDto summary, QNetworkReply::NetworkError error_type, QString error_str);
    void pingSignalError(OAIMyMessageDto summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use rootSignalError() instead")
    void rootSignalE(OAIMyMessageDto summary, QNetworkReply::NetworkError error_type, QString error_str);
    void rootSignalError(OAIMyMessageDto summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use temperatureSignalError() instead")
    void temperatureSignalE(OAIMyTemperatureDto summary, QNetworkReply::NetworkError error_type, QString error_str);
    void temperatureSignalError(OAIMyTemperatureDto summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use toggleLedSignalError() instead")
    void toggleLedSignalE(QString summary, QNetworkReply::NetworkError error_type, QString error_str);
    void toggleLedSignalError(QString summary, QNetworkReply::NetworkError error_type, const QString &error_str);

    Q_DECL_DEPRECATED_X("Use getLastPeriodicMessageSignalErrorFull() instead")
    void getLastPeriodicMessageSignalEFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void getLastPeriodicMessageSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pingSignalErrorFull() instead")
    void pingSignalEFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void pingSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use rootSignalErrorFull() instead")
    void rootSignalEFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void rootSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use temperatureSignalErrorFull() instead")
    void temperatureSignalEFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void temperatureSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use toggleLedSignalErrorFull() instead")
    void toggleLedSignalEFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void toggleLedSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);

    void abortRequestsSignal();
    void allPendingRequestsCompleted();

public Q_SLOTS:
    void tokenAvailable();
};

} // namespace OpenAPI
#endif
