/**
 * Service with Swagger-UI
 * C++/oat++ Web Service with Swagger-UI
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIMyTemperatureDto.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIMyTemperatureDto::OAIMyTemperatureDto(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIMyTemperatureDto::OAIMyTemperatureDto() {
    this->initializeModel();
}

OAIMyTemperatureDto::~OAIMyTemperatureDto() {}

void OAIMyTemperatureDto::initializeModel() {

    m_status_code_isSet = false;
    m_status_code_isValid = false;

    m_temperature_isSet = false;
    m_temperature_isValid = false;
}

void OAIMyTemperatureDto::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIMyTemperatureDto::fromJsonObject(QJsonObject json) {

    m_status_code_isValid = ::OpenAPI::fromJsonValue(m_status_code, json[QString("statusCode")]);
    m_status_code_isSet = !json[QString("statusCode")].isNull() && m_status_code_isValid;

    m_temperature_isValid = ::OpenAPI::fromJsonValue(m_temperature, json[QString("temperature")]);
    m_temperature_isSet = !json[QString("temperature")].isNull() && m_temperature_isValid;
}

QString OAIMyTemperatureDto::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIMyTemperatureDto::asJsonObject() const {
    QJsonObject obj;
    if (m_status_code_isSet) {
        obj.insert(QString("statusCode"), ::OpenAPI::toJsonValue(m_status_code));
    }
    if (m_temperature_isSet) {
        obj.insert(QString("temperature"), ::OpenAPI::toJsonValue(m_temperature));
    }
    return obj;
}

qint32 OAIMyTemperatureDto::getStatusCode() const {
    return m_status_code;
}
void OAIMyTemperatureDto::setStatusCode(const qint32 &status_code) {
    m_status_code = status_code;
    m_status_code_isSet = true;
}

bool OAIMyTemperatureDto::is_status_code_Set() const{
    return m_status_code_isSet;
}

bool OAIMyTemperatureDto::is_status_code_Valid() const{
    return m_status_code_isValid;
}

float OAIMyTemperatureDto::getTemperature() const {
    return m_temperature;
}
void OAIMyTemperatureDto::setTemperature(const float &temperature) {
    m_temperature = temperature;
    m_temperature_isSet = true;
}

bool OAIMyTemperatureDto::is_temperature_Set() const{
    return m_temperature_isSet;
}

bool OAIMyTemperatureDto::is_temperature_Valid() const{
    return m_temperature_isValid;
}

bool OAIMyTemperatureDto::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_status_code_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_temperature_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIMyTemperatureDto::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
