/**
 * Service with Swagger-UI
 * C++/oat++ Web Service with Swagger-UI
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIMyTemperatureDto.h
 *
 * 
 */

#ifndef OAIMyTemperatureDto_H
#define OAIMyTemperatureDto_H

#include <QJsonObject>


#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIMyTemperatureDto : public OAIObject {
public:
    OAIMyTemperatureDto();
    OAIMyTemperatureDto(QString json);
    ~OAIMyTemperatureDto() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint32 getStatusCode() const;
    void setStatusCode(const qint32 &status_code);
    bool is_status_code_Set() const;
    bool is_status_code_Valid() const;

    float getTemperature() const;
    void setTemperature(const float &temperature);
    bool is_temperature_Set() const;
    bool is_temperature_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    qint32 m_status_code;
    bool m_status_code_isSet;
    bool m_status_code_isValid;

    float m_temperature;
    bool m_temperature_isSet;
    bool m_temperature_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIMyTemperatureDto)

#endif // OAIMyTemperatureDto_H
