/**
 * Service with Swagger-UI
 * C++/oat++ Web Service with Swagger-UI
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIMyMessageDto.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIMyMessageDto::OAIMyMessageDto(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIMyMessageDto::OAIMyMessageDto() {
    this->initializeModel();
}

OAIMyMessageDto::~OAIMyMessageDto() {}

void OAIMyMessageDto::initializeModel() {

    m_status_code_isSet = false;
    m_status_code_isValid = false;

    m_message_isSet = false;
    m_message_isValid = false;
}

void OAIMyMessageDto::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIMyMessageDto::fromJsonObject(QJsonObject json) {

    m_status_code_isValid = ::OpenAPI::fromJsonValue(m_status_code, json[QString("statusCode")]);
    m_status_code_isSet = !json[QString("statusCode")].isNull() && m_status_code_isValid;

    m_message_isValid = ::OpenAPI::fromJsonValue(m_message, json[QString("message")]);
    m_message_isSet = !json[QString("message")].isNull() && m_message_isValid;
}

QString OAIMyMessageDto::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIMyMessageDto::asJsonObject() const {
    QJsonObject obj;
    if (m_status_code_isSet) {
        obj.insert(QString("statusCode"), ::OpenAPI::toJsonValue(m_status_code));
    }
    if (m_message_isSet) {
        obj.insert(QString("message"), ::OpenAPI::toJsonValue(m_message));
    }
    return obj;
}

qint32 OAIMyMessageDto::getStatusCode() const {
    return m_status_code;
}
void OAIMyMessageDto::setStatusCode(const qint32 &status_code) {
    m_status_code = status_code;
    m_status_code_isSet = true;
}

bool OAIMyMessageDto::is_status_code_Set() const{
    return m_status_code_isSet;
}

bool OAIMyMessageDto::is_status_code_Valid() const{
    return m_status_code_isValid;
}

QString OAIMyMessageDto::getMessage() const {
    return m_message;
}
void OAIMyMessageDto::setMessage(const QString &message) {
    m_message = message;
    m_message_isSet = true;
}

bool OAIMyMessageDto::is_message_Set() const{
    return m_message_isSet;
}

bool OAIMyMessageDto::is_message_Valid() const{
    return m_message_isValid;
}

bool OAIMyMessageDto::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_status_code_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_message_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIMyMessageDto::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
